### ISSUE TITLE
Fork exam repos

### ISSUE THREAD

**Issue by segerhult** [dalo-mdu/site#25]
Fork the exam repo to dalo.se

https://github.com/Roslund/OldExams

**Comment by Kurbitz** [comment]
There's an even more up to date fork of Roslunds old repo. Vestue has been updating https://github.com/Vestue/MDU-Exams for some time now. We could maybe collaborate with him and maintain the repo under the DALO org to improve longevity, passing the torch to future students.

**Comment by segerhult** [comment]
Nice! ill create a fork

**Comment by kngrektor** [comment]
Closing as we know have [this fork](https://github.com/dalo-mdu/MDU-OLD_Exams).

We should probably look into not treating it as a fork since GitHub hides it in the [repos list](https://github.com/orgs/dalo-mdu/repositories?type=source) by default.

Also this issue probably shouldn't be on the site repo. Maybe we can transfer it to the exams repo when it's no longer a fork.
